### PR TITLE
V1.2

### PR DESCRIPTION
**Pull request by robdockins**
Updates in preparation for new release.

### CODE REVIEW

**Comment by robdockins** [comment]
Hummm... pretty annoying to have `what4-transition-system` in this repository depend on `language-sally` which depends on `what4`.  Now we have to make coordinated changes in those two repos to bump the version number.

**Comment by Ptival** [comment]
Ah indeed, this sounds annoying. What do you think @atomb ?

**Comment by atomb** [comment]
Ah, this is tricky. Since the Sally MCMT format is essentially an extension of SMT-Lib, `language-sally` uses the What4 notion of SMT-Lib as a core building block.

I guess the easiest way to break the loop would be to leave the `What4.TransitionSystem` module in the `what4` repo, but move the `What4.TransitionSystem.Exporter.Sally` module into the `language-sally` repo. There's a certain logic to that structure.

**Review by kquick — APPROVED** [review]
Looks good overall, once you resolve the transition system dependencies.

**Comment by Ptival** [comment]
> I guess the easiest way to break the loop would be to leave the `What4.TransitionSystem` module in the `what4` repo, but move the `What4.TransitionSystem.Exporter.Sally` module into the `language-sally` repo. There's a certain logic to that structure.

I kind of like that, will give it a try.

**Comment by robdockins** [comment]
I think that's a good idea, but let's not hold up this PR/release for it.  For now, I think we can just relax the bounds and bump the submodule.

**Pull request merged**
